#####
avatar: https://img0.baidu.com/it/u=3928903079,1184629296&fm=26&fmt=auto
favicon:
preload: true #字体预加载
excerpt_length: 300 #自动生成的摘要长度 建议文章中手动使用 <!--more--> 效果更佳
tag_page_count: true #Tag页是否计数
mourn_mode: false #哀悼模式

# 主题颜色
theme_color:
  primary: red
  accent: red

# 搜索
search:
  local: true
  path: /search.xml
  placeholder: 请输入关键字

# Google Adsense广告代码
google_adsense:
  enabled: false #开启广告
  auto_ad: false #自动广告
  page_ad: false  #单页启用广告
  pub_id:
  footer_slot:
  sidebar_slot:
  banner_slot:

#####文章#####
# 文末结束语
passage_end_tag:
  enabled: true
  text: --- 本文结束 <i class="iconfont icon-heartbeat" style="font-size:24px;"></i> The End ---

# 数学公式渲染
math:
  enabled: true
  engine: mathjax ##可选渲染引擎：mathjax、katex
  mathjax:
    cdn: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    mhchem: true  #化学式扩展
  katex:
    cdn_css: https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css
    cdn_js: https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js
    auto_render: https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js

# mermaid图
mermaid:
  enable: true
  version: "8.4.8"
  startOnload: true  #default true
  theme: 'default'    #default, forest, dark, neutral.
##########

#####侧边栏#####
# 菜单
menu:
  home: / || icon-home
  标签: /tags/ || icon-bookmark
  categories: /categories/ || icon-folder
  archives: /archives/ || icon-archive
  tools: /tools/ || icon-tools
  about: /about/ || icon-user
  #gallery: /categories/图集/ || icon-gallery

# 社交链接
social:
  E-Mail: mailto:xiangdeyong@outlook.com || icon-mail
  GitHub: https://github.com/xiangdeyong || icon-github
  Steam: https://your.url || icon-steam
  Wechat: https://u.wechat.com/MJxvRtJr9EMckECaoPB6-go || icon-wechat
  # 此外还预置了以下社交图标，可直接仿照格式进行引用，如需其他图标请自行添加图标库或与我联系
  # icon-twitter、icon-facebook、icon-vk、icon-stack-overflow、icon-youtube、icon-Instagram、icon-skype
  # icon-qq、icon-wechat、icon-alipay、icon-paypal、icon-telegram、icon-twitch、icon-discord
  # icon-weibo

#友情链接
links:
  Meadow说明文档: https://garybear.cn/hexo-theme-meadow/
  「CloudBase Webify 提供网站托管服务」: https://webify.cloudbase.net/
##########

#####页脚#####
# 页脚
footer:
  since: 2015
  powered: true
  theme: true
  beian:
    enable: true
    icp:
  icon:
    enabled: true
    name: icon-heart
    color: "#d9333f"

# 不蒜子计数
busuanzi:
  site: true
  page: true
  busuanzi_js: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
##########

#####第三方服务#####
# 评论
comment:
  use:
    - gitalk
    - livere
  ## Gitalk
  gitalk_client_id: bc56e4c4e16ed36d9c86
  gitalk_client_secret: 58bd601dd20362342494d87a9105da980bcfcb77
  gitalk_repo: xiangDY-hexo-comments
  gitalk_owner: xiangdeyong
  gitalk_sid_type: location.pathname
  gitalk_distractionFreeMode: true
  ## Disqus
  disqus_shortname:
  ## Livere
  livere_data_uid:
  ## Valine
  valine_leancloud_app_id:
  valine_leancloud_app_key:
  valine_placeholder:
  valine_page_size:
  valine_avatar:
  valine_lang:
  valine_guest_info:
  valine_notify:
  valine_verify:
  ## 畅言
  changyan_app_id:
  changyan_app_key:
  changyan_sid_type:

# 分析
analytics:
  google_analytics:
    tracking_id:
    localhost_ignored: true
  baidu_site_id:
  cnzz_site_id:
  tencent_site_id:
##########
